/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.mx.uam.ayd.practica;

/**
 *
 * @author Ivan
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    Aplicacion aplicacion;

    public VentanaPrincipal(Aplicacion control) {
        initComponents();
        aplicacion = control;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarLibro = new javax.swing.JButton();
        buscarMaterial = new javax.swing.JButton();
        agregarAutor = new javax.swing.JButton();
        eliminarMaterial = new javax.swing.JButton();
        agregarRevista = new javax.swing.JButton();
        listarMaterial = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agregarLibro.setText("Agregar Libro");
        agregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLibroActionPerformed(evt);
            }
        });

        buscarMaterial.setText("Buscar Material");
        buscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMaterialActionPerformed(evt);
            }
        });

        agregarAutor.setText("Agregar Autor");
        agregarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAutorActionPerformed(evt);
            }
        });

        eliminarMaterial.setText("Eliminar Material");
        eliminarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMaterialActionPerformed(evt);
            }
        });

        agregarRevista.setText("Agregar Revista");
        agregarRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarRevistaActionPerformed(evt);
            }
        });

        listarMaterial.setText("Listar Material");
        listarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMaterialActionPerformed(evt);
            }
        });

        jLabel1.setText("Libreria Material");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregarLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarRevista)
                    .addComponent(agregarAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buscarMaterial)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(listarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eliminarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarMaterial))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eliminarMaterial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listarMaterial)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(agregarRevista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(110, 110, 110))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLibroActionPerformed
        aplicacion.agregarRevista();
    }//GEN-LAST:event_agregarLibroActionPerformed

    private void buscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMaterialActionPerformed
        aplicacion.buscarMaterial();
    }//GEN-LAST:event_buscarMaterialActionPerformed

    private void agregarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAutorActionPerformed
        aplicacion.agregarAutor();
    }//GEN-LAST:event_agregarAutorActionPerformed

    private void eliminarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMaterialActionPerformed
        aplicacion.quitarMaterial();
    }//GEN-LAST:event_eliminarMaterialActionPerformed

    private void agregarRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarRevistaActionPerformed
        aplicacion.agregarRevista();
    }//GEN-LAST:event_agregarRevistaActionPerformed

    private void listarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMaterialActionPerformed
        aplicacion.listarMateriales();
    }//GEN-LAST:event_listarMaterialActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarAutor;
    private javax.swing.JButton agregarLibro;
    private javax.swing.JButton agregarRevista;
    private javax.swing.JButton buscarMaterial;
    private javax.swing.JButton eliminarMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listarMaterial;
    // End of variables declaration//GEN-END:variables
}
